# Fichier : questions_data.py

data = {
    "Facile": [
        {"q": "Quel est l'arbre fruitier le plus répandu en Guadeloupe ?", "options": ["Bananier", "Cocotier", "Manguier", "Goyavier"], "r": "Bananier"},
        {"q": "Quel est l'animal le plus répandu en Guadeloupe ?", "options": ["Être humain", "Anolis (lézard)", "Moustique", "Rat"], "r": "Être humain"},
        {"q": "Quel est le plus grand océan de la planète ?", "options": ["Océan Pacifique", "Océan Atlantique", "Océan Indien", "Océan Austral"], "r": "Océan Pacifique"},
        {"q": "Quel est le fruit le plus riche en sucre ?", "options": ["Datte", "Figue sèche", "Raisin sec", "Banane mûre"], "r": "Datte"},
        {"q": "Quel animal est célèbre pour construire des barrages sur les rivières ?", "options": ["Le castor", "La loutre", "Le ragondin", "Le canard"], "r": "Le castor"},
        {"q": "Quelle planète de notre système solaire est surnommée 'la planète bleue' ?", "options": ["La Terre", "Neptune", "Uranus", "Vénus"], "r": "La Terre"},
        {"q": "Comment s'appelle le bébé du mouton ?", "options": ["L'agneau", "Le chevreau", "Le poulain", "Le veau"], "r": "L'agneau"},
        {"q": "Quel oiseau blanc est universellement reconnu comme le symbole de la paix ?", "options": ["La colombe", "Le cygne", "La mouette", "La cigogne"], "r": "La colombe"},
        {"q": "Combien de pattes possède une araignée ?", "options": ["8", "6", "10", "12"], "r": "8"},
        {"q": "Quel est le plus grand mammifère terrestre actuel ?", "options": ["L'éléphant d'Afrique", "Le rhinocéros blanc", "L'hippopotame", "La girafe"], "r": "L'éléphant d'Afrique"},
        {"q": "Où vivent les ours polaires à l'état naturel ?", "options": ["En Arctique (Pôle Nord)", "En Antarctique (Pôle Sud)", "Dans les Andes", "En Sibérie uniquement"], "r": "En Arctique (Pôle Nord)"},
        {"q": "Quel est l'animal terrestre avec le plus long cou ?", "options": ["La girafe", "L'autruche", "Le lama", "Le chameau"], "r": "La girafe"},
        {"q": "Comment appelle-t-on un animal qui mange à la fois des plantes et de la viande ?", "options": ["Omnivore", "Carnivore", "Herbivore", "Frugivore"], "r": "Omnivore"},
        {"q": "Quelle est la couleur du sang chez la majorité des insectes ?", "options": ["Incolore ou jaunâtre", "Rouge", "Bleu", "Vert"], "r": "Incolore ou jaunâtre"},
        {"q": "Quel est le plus grand animal vivant sur notre planète ?", "options": ["L'éléphant", "La baleine bleue", "Le requin baleine", "La girafe"], "r": "La baleine bleue"},
        {"q": "Quel insecte est célèbre pour sa production de miel ?", "options": ["La guêpe", "Le bourdon", "L'abeille", "La fourmi"], "r": "L'abeille"},
        {"q": "Comment appelle-t-on le long sommeil de certains animaux pendant l'hiver ?", "options": ["La somnolence", "La migration", "L'hibernation", "L'estivation"], "r": "L'hibernation"},
        {"q": "Quel est le continent recouvert de glace situé au pôle Sud ?", "options": ["L'Arctique", "L'Antarctique", "L'Océanie", "Le Groenland"], "r": "L'Antarctique"},
        {"q": "Quel grand félin sauvage possède un pelage rayé orange et noir ?", "options": ["Le lion", "Le léopard", "Le guépard", "Le tigre"], "r": "Le tigre"},
        {"q": "De quelle couleur sont les flamants roses à leur naissance ?", "options": ["Roses", "Blancs ou gris", "Noirs", "Marrons"], "r": "Blancs ou gris"},
        {"q": "Quel reptile est connu pour porter sa maison sur son dos ?", "options": ["Le crocodile", "L'iguane", "La tortue", "Le caméléon"], "r": "La tortue"},
        {"q": "Quel arbre est célèbre pour produire des glands que mangent les écureuils ?", "options": ["Le chêne", "Le pin", "Le pommier", "Le sapin"], "r": "Le chêne"},
        {"q": "Quel animal marin est souvent qualifié de très intelligent et joueur ?", "options": ["Le requin", "Le dauphin", "La raie", "Le thon"], "r": "Le dauphin"},
        {"q": "Quel oiseau symbolise souvent les États-Unis ?", "options": ["Le condor", "L'aigle royal", "Le pygargue à tête blanche", "Le faucon"], "r": "Le pygargue à tête blanche"},
        {"q": "Combien de pattes a un insecte comme la fourmi ?", "options": ["4", "6", "8", "10"], "r": "6"},
        {"q": "Comment s'appelle l'endroit où un fleuve se jette dans la mer ?", "options": ["La source", "L'estuaire", "Le confluent", "La cascade"], "r": "L'estuaire"},
        {"q": "Quel animal a des rayures noires et blanches ?", "options": ["Le zèbre", "Le tigre", "L'okapi", "Le panda"], "r": "Le zèbre"},
        {"q": "Que récoltent les abeilles sur les fleurs pour fabriquer du miel ?", "options": ["Le nectar", "La sève", "La rosée", "Le sirop"], "r": "Le nectar"},
        {"q": "Quel est le plus grand oiseau vivant aujourd'hui (qui court très vite mais ne vole pas) ?", "options": ["L'autruche", "L'émeu", "Le pélican", "Le flamant rose"], "r": "L'autruche"},
        {"q": "Comment s'appelle le bébé du chien ?", "options": ["Le chiot", "Le louveteau", "Le poulain", "Le chaton"], "r": "Le chiot"},
        {"q": "Quel animal sauvage est doté d'une longue trompe et de grandes oreilles ?", "options": ["L'éléphant", "Le rhinocéros", "L'hippopotame", "Le tapir"], "r": "L'éléphant"},
        {"q": "Que deviennent les têtards en grandissant ?", "options": ["Des grenouilles", "Des poissons", "Des lézards", "Des serpents"], "r": "Des grenouilles"},
        {"q": "Quel est l'animal souvent surnommé le 'roi des animaux' ?", "options": ["Le lion", "Le tigre", "L'aigle", "L'ours"], "r": "Le lion"},
        {"q": "Sur quel continent vivent les kangourous à l'état sauvage ?", "options": ["L'Australie", "L'Afrique", "L'Amérique du Sud", "L'Asie"], "r": "L'Australie"},
        {"q": "Avec quoi les poissons se dirigent-ils pour nager ?", "options": ["Leurs nageoires", "Leurs branchies", "Leurs écailles", "Leurs pattes antérieures"], "r": "Leurs nageoires"},
        {"q": "Quel est l'astre qui nous éclaire le jour et chauffe la Terre ?", "options": ["Le Soleil", "La Lune", "Jupiter", "L'Étoile Polaire"], "r": "Le Soleil"},
        {"q": "Quel petit insecte rouge à points noirs est souvent considéré comme un porte-bonheur ?", "options": ["La coccinelle", "Le scarabée", "La punaise", "Le gendarme"], "r": "La coccinelle"},
        {"q": "Dans quel milieu naturel trouve-t-on le plus de coraux ?", "options": ["Dans les océans", "Dans les lacs", "Dans les rivières", "Dans les montagnes"], "r": "Dans les océans"},
        {"q": "Quel animal marin noir et blanc est parfois appelé 'baleine tueuse' ?", "options": ["L'orque", "Le grand requin blanc", "Le béluga", "Le narval"], "r": "L'orque"},
        {"q": "Quel légume orange, poussant dans la terre, est réputé pour être adoré des lapins ?", "options": ["La carotte", "Le navet", "La patate douce", "Le potiron"], "r": "La carotte"},
        {"q": "Quelle saison est connue pour la chute des feuilles des arbres et le raccourcissement des jours ?", "options": ["Le printemps", "L'été", "L'automne", "L'hiver"], "r": "L'automne"},
        {"q": "Quel animal baveux et lent porte une coquille en spirale sur son dos ?", "options": ["La limace", "L'escargot", "Le bernard-l'ermite", "La tortue"], "r": "L'escargot"},
        {"q": "Comment s'appelle la montagne qui peut entrer en éruption et cracher de la lave ?", "options": ["Un glacier", "Un volcan", "Un cratère", "Un canyon"], "r": "Un volcan"},
        {"q": "Quel animal bondissant se déplace en sautant avec ses puissantes pattes arrière en Australie ?", "options": ["Le kangourou", "Le lapin", "La grenouille", "L'antilope"], "r": "Le kangourou"},
        {"q": "Quel oiseau au plumage noir est souvent associé à la sorcellerie ou à Halloween ?", "options": ["Le corbeau", "La pie", "Le pigeon", "Le merle"], "r": "Le corbeau"},
        {"q": "Quelle petite créature verte saute et coasse près des mares ?", "options": ["Le lézard", "La grenouille", "Le triton", "La salamandre"], "r": "La grenouille"},
        {"q": "Sur quel arbre fruitier poussent les pommes ?", "options": ["Le poirier", "Le cerisier", "Le pommier", "Le prunier"], "r": "Le pommier"},
        {"q": "Comment appelle-t-on le petit du chat ?", "options": ["Le chiot", "Le chaton", "Le lionceau", "Le poulain"], "r": "Le chaton"},
        {"q": "Quel grand mammifère des forêts aime manger du miel et peut se tenir sur ses pattes arrière ?", "options": ["Le loup", "Le sanglier", "L'ours", "Le renard"], "r": "L'ours"},
        {"q": "Quel est l'astre qui brille dans le ciel la nuit et change de forme (croissant, pleine...) ?", "options": ["Le Soleil", "La Lune", "Mars", "L'Étoile Polaire"], "r": "La Lune"},
        {"q": "Quelle partie de la plante pousse généralement sous la terre ?", "options": ["Les racines", "Les feuilles", "Les tiges", "Les fleurs"], "r": "Les racines"},
        {"q": "Quel petit rongeur est célèbre pour cacher des glands et des noisettes ?", "options": ["L'écureuil", "Le rat", "La souris", "Le hamster"], "r": "L'écureuil"},
        {"q": "Quel animal de la ferme donne le lait que nous buvons le plus souvent ?", "options": ["La vache", "La poule", "Le cochon", "Le cheval"], "r": "La vache"},
        {"q": "Comment appelle-t-on l'eau gelée qui tombe du ciel en hiver ?", "options": ["La neige", "La pluie", "La rosée", "Le brouillard"], "r": "La neige"},
        {"q": "Quel oiseau de basse-cour est célèbre pour faire 'coin-coin' ?", "options": ["Le canard", "La poule", "Le dindon", "L'oie"], "r": "Le canard"},
        {"q": "Quel animal marin a de longs bras et jette de l'encre quand il a peur ?", "options": ["La pieuvre", "Le requin", "Le dauphin", "La méduse"], "r": "La pieuvre"},
        {"q": "Comment appelle-t-on le petit de la vache ?", "options": ["Le veau", "Le poulain", "Le porcelet", "L'agneau"], "r": "Le veau"},
        {"q": "Quel insecte coloré commence sa vie en tant que chenille ?", "options": ["Le papillon", "La fourmi", "La sauterelle", "La mouche"], "r": "Le papillon"},
        {"q": "Quel oiseau des glaces ne sait pas voler mais nage très bien ?", "options": ["Le manchot", "L'aigle", "Le perroquet", "Le hibou"], "r": "Le manchot"},
        {"q": "Quel grand singe d'Afrique est notre plus proche cousin ?", "options": ["Le chimpanzé", "Le lémurien", "Le babouin", "Le macaque"], "r": "Le chimpanzé"},
        {"q": "Quelle est la couleur du ciel lorsqu'il n'y a pas de nuages en plein jour ?", "options": ["Bleu", "Vert", "Rouge", "Jaune"], "r": "Bleu"},
        {"q": "Comment appelle-t-on un tremblement de terre ?", "options": ["Un séisme", "Une tempête", "Un tsunami", "Une tornade"], "r": "Un séisme"}
    ],
    "Normal": [
        {"q": "Quel est le volatile le plus rapide ?", "options": ["Faucon pèlerin", "Martinet noir", "Aigle royal", "Hirondelle"], "r": "Faucon pèlerin"},
        {"q": "Comment s'appelle l'étude du comportement animal ?", "options": ["Éthologie", "Psychologie animale", "Sociobiologie", "Neuroéthologie"], "r": "Éthologie"},
        {"q": "Quel est le biome dominant en Afrique centrale ?", "options": ["Forêt tropicale humide", "Savane tropicale", "Zones humides", "Forêt de montagne"], "r": "Forêt tropicale humide"},
        {"q": "Comment appelle-t-on le processus par lequel les plantes créent leur énergie grâce au soleil ?", "options": ["La photosynthèse", "La respiration", "La méiose", "La pollinisation"], "r": "La photosynthèse"},
        {"q": "Quel est le nom de la substance qui donne aux feuilles leur couleur verte ?", "options": ["La chlorophylle", "La mélanine", "Le carotène", "L'hémoglobine"], "r": "La chlorophylle"},
        {"q": "Quel est le plus grand désert chaud du monde ?", "options": ["Le Sahara", "Le Gobi", "Le Kalahari", "Le Mojave"], "r": "Le Sahara"},
        {"q": "Par quel organe les poissons respirent-ils sous l'eau ?", "options": ["Les branchies", "Les poumons", "La peau", "Les nageoires"], "r": "Les branchies"},
        {"q": "Quel est l'animal terrestre le plus rapide sur une courte distance ?", "options": ["Le guépard", "Le lion", "L'antilope", "Le cheval"], "r": "Le guépard"},
        {"q": "De quelle plante se nourrit presque exclusivement le panda géant ?", "options": ["Le bambou", "L'eucalyptus", "La fougère", "L'acacia"], "r": "Le bambou"},
        {"q": "Comment qualifie-t-on un arbre qui perd ses feuilles en automne ?", "options": ["Caduc", "Persistant", "Conifère", "Endémique"], "r": "Caduc"},
        {"q": "Quel insecte est responsable de la transmission du paludisme ?", "options": ["Le moustique (Anophèle)", "La mouche tsé-tsé", "La tique", "La puce"], "r": "Le moustique (Anophèle)"},
        {"q": "Quel est le plus long fleuve d'Amérique du Sud ?", "options": ["L'Amazone", "Le Paraná", "L'Orénoque", "Le Colorado"], "r": "L'Amazone"},
        {"q": "Quel oiseau marin noir et blanc est incapable de voler mais nage très bien ?", "options": ["Le manchot", "Le pélican", "Le goéland", "L'albatros"], "r": "Le manchot"},
        {"q": "Quel mammifère volant utilise l'écholocation pour se repérer dans le noir ?", "options": ["Le hibou", "La chouette", "La chauve-souris", "L'écureuil volant"], "r": "La chauve-souris"},
        {"q": "Comment s'appelle la transformation d'une chenille en papillon ?", "options": ["L'évolution", "La métamorphose", "La mutation", "La mue"], "r": "La métamorphose"},
        {"q": "Quel est le plus haut sommet du monde au-dessus du niveau de la mer ?", "options": ["Le Mont Blanc", "Le Kilimandjaro", "L'Everest", "Le K2"], "r": "L'Everest"},
        {"q": "Quel marsupial australien se nourrit presque exclusivement de feuilles d'eucalyptus ?", "options": ["Le kangourou", "Le wombat", "Le diable de Tasmanie", "Le koala"], "r": "Le koala"},
        {"q": "Quelle est la plus grande structure vivante sur Terre, visible depuis l'espace ?", "options": ["La forêt amazonienne", "La Grande Muraille de Chine", "La Grande Barrière de corail", "Le désert du Sahara"], "r": "La Grande Barrière de corail"},
        {"q": "Quel mot désigne l'ensemble des différentes espèces vivantes sur notre planète ?", "options": ["La biosphère", "L'écologie", "La biodiversité", "L'écosystème"], "r": "La biodiversité"},
        {"q": "Quel cétacé possède une longue défense torsadée sur la tête, le faisant ressembler à une licorne ?", "options": ["Le béluga", "Le narval", "Le morse", "L'orque"], "r": "Le narval"},
        {"q": "Quelle mer est tellement riche en sel qu'on y flotte sans aucun effort ?", "options": ["La Mer Rouge", "La Mer Morte", "La Mer Méditerranée", "La Mer Noire"], "r": "La Mer Morte"},
        {"q": "Comment s'appelle la perte totale d'une espèce animale ou végétale ?", "options": ["L'éradication", "L'extinction", "La disparition", "L'évolution"], "r": "L'extinction"},
        {"q": "Quelle est l'énergie principale qui fait fonctionner le cycle de l'eau sur Terre ?", "options": ["Le vent", "La gravité", "Le soleil", "La lune"], "r": "Le soleil"},
        {"q": "Quel arbre majestueux de la savane africaine peut stocker des milliers de litres d'eau dans son tronc ?", "options": ["Le baobab", "L'acacia", "L'eucalyptus", "Le fromager"], "r": "Le baobab"},
        {"q": "Quel est le nom scientifique des 'pluies' causées par la pollution atmosphérique qui abîment les forêts ?", "options": ["Les pluies toxiques", "Les pluies acides", "Les pluies carboniques", "Les pluies grises"], "r": "Les pluies acides"},
        {"q": "Quel est le plus grand carnivore terrestre vivant aujourd'hui ?", "options": ["L'ours polaire", "Le tigre de Sibérie", "Le lion d'Afrique", "Le grizzli"], "r": "L'ours polaire"},
        {"q": "De quel arbre provient le célèbre sirop canadien ?", "options": ["L'érable", "Le bouleau", "Le chêne", "Le pin"], "r": "L'érable"},
        {"q": "Combien de compartiments principaux possède l'estomac d'une vache ?", "options": ["4", "1", "2", "3"], "r": "4"},
        {"q": "Quelle est la nourriture principale de la gigantesque baleine bleue ?", "options": ["Le krill (petites crevettes)", "Les pingouins", "Les requins", "Les algues géantes"], "r": "Le krill (petites crevettes)"},
        {"q": "Comment appelle-t-on les animaux qui dorment le jour et vivent la nuit ?", "options": ["Les animaux nocturnes", "Les animaux diurnes", "Les animaux crépusculaires", "Les animaux endormis"], "r": "Les animaux nocturnes"},
        {"q": "À quelle famille d'animaux appartient la grenouille ?", "options": ["Les amphibiens", "Les reptiles", "Les mammifères", "Les poissons"], "r": "Les amphibiens"},
        {"q": "Quel oiseau exotique est célèbre pour sa capacité à imiter la voix humaine ?", "options": ["Le perroquet", "Le toucan", "Le colibri", "Le cacatoès"], "r": "Le perroquet"},
        {"q": "Quel est le gaz le plus abondant dans l'atmosphère terrestre (environ 78%) ?", "options": ["L'azote", "L'oxygène", "Le dioxyde de carbone", "L'hélium"], "r": "L'azote"},
        {"q": "Sur quelle grande île vivent les lémuriens à l'état naturel ?", "options": ["Madagascar", "L'Australie", "Le Sri Lanka", "La Nouvelle-Zélande"], "r": "Madagascar"},
        {"q": "Quel océan se trouve entre l'Afrique et l'Australie ?", "options": ["L'océan Indien", "L'océan Atlantique", "L'océan Pacifique", "L'océan Arctique"], "r": "L'océan Indien"},
        {"q": "Quelle plante carnivore possède des 'mâchoires' qui se referment sur les insectes ?", "options": ["La dionée attrape-mouche", "Le népenthès", "La drosera", "L'orchidée fantôme"], "r": "La dionée attrape-mouche"},
        {"q": "Comment s'appelle l'endroit sous-terrain où l'eau douce est naturellement stockée ?", "options": ["Une nappe phréatique", "Un geyser", "Un glacier", "Un estuaire"], "r": "Une nappe phréatique"},
        {"q": "Comment s'appelle le phénomène naturel où la Lune passe exactement devant le Soleil ?", "options": ["Une éclipse solaire", "Une aurore boréale", "Un solstice", "Un équinoxe"], "r": "Une éclipse solaire"},
        {"q": "Quel est le plus grand félin sauvage du continent américain, célèbre pour son pelage tacheté ?", "options": ["Le puma", "L'ocelot", "Le jaguar", "Le lynx"], "r": "Le jaguar"},
        {"q": "Quelle pierre précieuse extrêmement dure est formée uniquement de carbone soumis à une forte pression ?", "options": ["Le rubis", "Le saphir", "Le diamant", "L'émeraude"], "r": "Le diamant"},
        {"q": "Quel nom donne-t-on au mâle de l'abeille ?", "options": ["Le bourdon", "Le frelon", "La guêpe", "Le faux bourdon"], "r": "Le faux bourdon"},
        {"q": "Quel animal marin en forme d'étoile possède généralement 5 bras ?", "options": ["L'oursin", "L'anémone", "L'étoile de mer", "Le concombre de mer"], "r": "L'étoile de mer"},
        {"q": "Comment s'appelle le grand rapace des Andes d'Amérique du Sud, charognard à la collerette blanche ?", "options": ["Le condor", "L'aigle royal", "Le vautour fauve", "Le faucon pèlerin"], "r": "Le condor"},
        {"q": "Quel type de nuage blanc et floconneux ressemble à de gros moutons de coton dans le ciel ?", "options": ["Le stratus", "Le cirrus", "Le cumulus", "Le cumulonimbus"], "r": "Le cumulus"},
        {"q": "Quel arbre est le symbole national du Liban, figurant même sur son drapeau ?", "options": ["L'olivier", "Le cèdre", "Le palmier", "Le cyprès"], "r": "Le cèdre"},
        {"q": "Quel reptile capable de changer de couleur a les yeux qui bougent indépendamment l'un de l'autre ?", "options": ["L'iguane", "Le caméléon", "Le gecko", "Le varan"], "r": "Le caméléon"},
        {"q": "Quelle région du monde est surnommée le 'poumon de la Terre' ?", "options": ["La toundra sibérienne", "La forêt amazonienne", "La savane africaine", "La grande barrière de corail"], "r": "La forêt amazonienne"},
        {"q": "Quel grand oiseau blanc avec une poche sous le bec plonge pour pêcher des poissons ?", "options": ["Le pélican", "Le cygne", "L'albatros", "Le héron"], "r": "Le pélican"},
        {"q": "Comment appelle-t-on la science qui étudie le climat et la météo ?", "options": ["La géologie", "La sismologie", "La météorologie", "L'astronomie"], "r": "La météorologie"},
        {"q": "Quel arbre est connu pour produire des pommes de pin ?", "options": ["Le pin", "Le chêne", "Le saule", "L'érable"], "r": "Le pin"},
        {"q": "Comment appelle-t-on le passage de l'eau de l'état liquide à l'état gazeux ?", "options": ["L'évaporation", "La condensation", "La fusion", "La solidification"], "r": "L'évaporation"},
        {"q": "Quel est le plus grand reptile vivant au monde ?", "options": ["Le crocodile marin", "Le varan de Komodo", "L'anaconda", "La tortue luth"], "r": "Le crocodile marin"},
        {"q": "Quel grand oiseau charognard a souvent la tête dépourvue de plumes ?", "options": ["Le vautour", "Le faucon", "Le hibou", "Le cygne"], "r": "Le vautour"},
        {"q": "Quel gaz les êtres humains expirent-ils après avoir respiré ?", "options": ["Le dioxyde de carbone", "L'oxygène", "L'azote", "L'hélium"], "r": "Le dioxyde de carbone"},
        {"q": "Quelles sont les chutes d'eau les plus hautes du monde, situées au Venezuela ?", "options": ["Le Salto Ángel", "Les chutes du Niagara", "Les chutes Victoria", "Les chutes d'Iguaçu"], "r": "Le Salto Ángel"},
        {"q": "Quel est l'océan le plus petit et le moins profond ?", "options": ["L'océan Arctique", "L'océan Indien", "L'océan Atlantique", "L'océan Austral"], "r": "L'océan Arctique"},
        {"q": "Comment s'appelle le groupe auquel appartiennent les loups qui chassent ensemble ?", "options": ["Une meute", "Un troupeau", "Un essaim", "Une colonie"], "r": "Une meute"},
        {"q": "Quel reptile est le fameux dragon de Komodo ?", "options": ["Un lézard", "Un serpent", "Un crocodile", "Une tortue"], "r": "Un lézard"},
        {"q": "Comment appelle-t-on la couche la plus externe de la Terre, sur laquelle nous marchons ?", "options": ["La croûte terrestre", "Le manteau", "Le noyau", "La lithosphère"], "r": "La croûte terrestre"},
        {"q": "Quelle petite créature construit des récifs sous-marins spectaculaires ?", "options": ["Le corail", "L'éponge", "L'huître", "Le plancton"], "r": "Le corail"},
        {"q": "Dans quel milieu naturel poussent les cactus géants saguaros ?", "options": ["Le désert", "La forêt tropicale", "La toundra", "La mangrove"], "r": "Le désert"}
    ],
    "Difficile": [
        {"q": "Combien y a-t-il de plages dans le monde ?", "options": ["Impossible à déterminer précisément", "Plusieurs dizaines de milliers", "Plus de 100 000", "Plusieurs centaines de milliers"], "r": "Impossible à déterminer précisément"},
        {"q": "Quel gaz est majoritairement responsable de l'effet de serre naturel ?", "options": ["Vapeur d'eau (H2O)", "Dioxyde de carbone (CO2)", "Méthane (CH4)", "Ozone (O3)"], "r": "Vapeur d'eau (H2O)"},
        {"q": "Quel animal possède le plus gros cerveau en proportion de son corps ?", "options": ["Fourmi", "Dauphin", "Corbeau", "Pieuvre"], "r": "Fourmi"},
        {"q": "Quelle couche de l'atmosphère contient la couche d'ozone ?", "options": ["Stratosphère", "Troposphère", "Mésosphère", "Thermosphère"], "r": "Stratosphère"},
        {"q": "Quel arbre d'origine asiatique est souvent considéré comme un 'fossile vivant' ?", "options": ["Le Ginkgo biloba", "Le Baobab", "Le Séquoia", "Le Bonsaï"], "r": "Le Ginkgo biloba"},
        {"q": "Quel est le nom scientifique de l'étude des champignons ?", "options": ["La mycologie", "La bryologie", "La cryptogamie", "L'herpétologie"], "r": "La mycologie"},
        {"q": "Quel est le seul mammifère au monde recouvert d'écailles ?", "options": ["Le pangolin", "Le tatou", "L'ornithorynque", "Le paresseux"], "r": "Le pangolin"},
        {"q": "Quelle est la fleur la plus grande et la plus malodorante du monde ?", "options": ["La Rafflesia arnoldii", "L'Arum titan", "Le Nénuphar géant", "L'Orchidée singe"], "r": "La Rafflesia arnoldii"},
        {"q": "À quelle profondeur maximale s'enfonce la fosse des Mariannes, l'endroit le plus profond de l'océan ?", "options": ["Environ 11 000 mètres", "Environ 8 000 mètres", "Environ 15 000 mètres", "Environ 5 000 mètres"], "r": "Environ 11 000 mètres"},
        {"q": "Quel est l'animal marin considéré comme le plus venimeux au monde ?", "options": ["La méduse-boîte (guêpe de mer)", "Le poisson-pierre", "Le serpent marin à nez plat", "La pieuvre à anneaux bleus"], "r": "La méduse-boîte (guêpe de mer)"},
        {"q": "Quel pourcentage de la surface de la Terre est couvert par les océans ?", "options": ["Environ 71%", "Environ 50%", "Environ 85%", "Environ 62%"], "r": "Environ 71%"},
        {"q": "Quel oiseau possède la plus grande envergure au monde (jusqu'à 3,5 mètres) ?", "options": ["L'albatros hurleur", "Le condor des Andes", "L'aigle martial", "Le pélican frisé"], "r": "L'albatros hurleur"},
        {"q": "Quel est l'âge approximatif de la planète Terre ?", "options": ["4,5 milliards d'années", "13,8 milliards d'années", "2 milliards d'années", "65 millions d'années"], "r": "4,5 milliards d'années"},
        {"q": "Quelle est la couleur du sang des pieuvres et des calmars ?", "options": ["Bleu", "Rouge", "Vert", "Transparent"], "r": "Bleu"},
        {"q": "Quel est l'oiseau qui pond le plus gros œuf par rapport à sa propre taille ?", "options": ["L'autruche", "Le kiwi", "L'émeu", "Le casoar"], "r": "Le kiwi"},
        {"q": "Quel était le nom du supercontinent unique qui existait il y a environ 300 millions d'années ?", "options": ["La Pangée", "Le Gondwana", "La Laurasia", "L'Atlantide"], "r": "La Pangée"},
        {"q": "Quelle espèce détient le record du plus grand arbre du monde en hauteur (souvent un Séquoia à feuilles d'if) ?", "options": ["Général Sherman", "Hyperion", "Mathusalem", "L'Arbre de Ténéré"], "r": "Hyperion"},
        {"q": "En biologie marine, quel est le nom de la zone océanique où la lumière ne pénètre plus (en dessous de 200m) ?", "options": ["La zone pélagique", "La zone benthique", "La zone aphotique", "La zone néritique"], "r": "La zone aphotique"},
        {"q": "Combien de cœurs possède une pieuvre ?", "options": ["1", "2", "3", "4"], "r": "3"},
        {"q": "Que signifie le sigle de l'ONG mondiale 'WWF' ?", "options": ["World Wildlife Fund", "World Water Foundation", "Wildlife World Federation", "World Wood Forest"], "r": "World Wildlife Fund"},
        {"q": "Quel est le mammifère marin capable de plonger le plus profondément et le plus longtemps (jusqu'à près de 3000m) ?", "options": ["Le grand cachalot", "La baleine bleue", "La baleine à bec de Cuvier", "L'éléphant de mer"], "r": "La baleine à bec de Cuvier"},
        {"q": "Quel phénomène météorologique destructeur est classé selon l'échelle de Fujita ?", "options": ["Les ouragans", "Les séismes", "Les tornades", "Les tsunamis"], "r": "Les tornades"},
        {"q": "Comment s'appelle l'étage supérieur de la forêt tropicale qui capte l'essentiel de la lumière du soleil ?", "options": ["Le sous-bois", "La canopée", "La litière", "La strate arbustive"], "r": "La canopée"},
        {"q": "Combien de temps certaines cigales périodiques nord-américaines (Magicicada) vivent-elles sous terre avant de sortir ?", "options": ["2 à 3 ans", "7 ou 9 ans", "13 ou 17 ans", "Plus de 25 ans"], "r": "13 ou 17 ans"},
        {"q": "Quel reptile endémique des îles Galápagos est le seul lézard marin au monde ?", "options": ["Le varan de Komodo", "L'iguane marin", "Le crocodile marin", "Le scinque aquatique"], "r": "L'iguane marin"},
        {"q": "Quelle roche sédimentaire combustible est formée par l'accumulation et la dégradation de matière végétale sur des millions d'années ?", "options": ["Le pétrole", "Le gaz naturel", "Le charbon", "Le granit"], "r": "Le charbon"},
        {"q": "Quel est le seul oiseau capable de voler en marche arrière ?", "options": ["Le colibri", "Le martinet", "Le faucon", "L'hirondelle"], "r": "Le colibri"},
        {"q": "Quel est le lac le plus profond du monde (atteignant plus de 1600m de profondeur) ?", "options": ["Le lac Baïkal", "Le lac Supérieur", "Le lac Victoria", "Le lac Titicaca"], "r": "Le lac Baïkal"},
        {"q": "Quel animal effectue la plus longue migration au monde (plus de 70 000 km par an) ?", "options": ["La sterne arctique", "La baleine grise", "Le monarque (papillon)", "Le caribou"], "r": "La sterne arctique"},
        {"q": "Comment s'appelle l'étude scientifique spécifique des arbres ?", "options": ["La dendrologie", "La botanique", "L'agronomie", "L'arboriculture"], "r": "La dendrologie"},
        {"q": "En dehors de l'ornithorynque, quel autre mammifère étonnant pond des œufs ?", "options": ["L'échidné", "Le pangolin", "Le wombat", "Le tapir"], "r": "L'échidné"},
        {"q": "Quel est le serpent terrestre le plus venimeux au monde ?", "options": ["Le taïpan du désert", "Le mamba noir", "Le cobra royal", "Le crotale diamantin"], "r": "Le taïpan du désert"},
        {"q": "Quel pourcentage de l'eau sur Terre est de l'eau douce (non salée) ?", "options": ["Environ 3%", "Environ 10%", "Environ 25%", "Environ 1%"], "r": "Environ 3%"},
        {"q": "Comment s'appelle le superocéan préhistorique massif qui entourait la Pangée ?", "options": ["La Panthalassa", "La Téthys", "L'océan Iapetus", "La mer de Béring"], "r": "La Panthalassa"},
        {"q": "Quel animal possède le plus grand nombre de dents (des milliers sur sa langue râpeuse) ?", "options": ["L'escargot", "Le grand requin blanc", "Le crocodile marin", "Le piranha"], "r": "L'escargot"},
        {"q": "Quelle couche de la Terre se trouve immédiatement en dessous de la croûte terrestre ?", "options": ["Le manteau", "Le noyau externe", "Le noyau interne", "La lithosphère"], "r": "Le manteau"},
        {"q": "Quel champignon gigantesque est considéré comme le plus grand organisme vivant sur Terre en surface ?", "options": ["L'armillaire d'Ostoya", "Le cèpe de Bordeaux", "La truffe noire", "Le mycélium titan"], "r": "L'armillaire d'Ostoya"},
        {"q": "Comment s'appelle le processus par lequel le vent ou l'eau use et transforme les roches ?", "options": ["L'érosion", "La sédimentation", "La subduction", "La tectonique"], "r": "L'érosion"},
        {"q": "Quel marsupial australien est célèbre pour faire des excréments en forme de cubes ?", "options": ["Le koala", "Le wombat", "Le kangourou", "Le quokka"], "r": "Le wombat"},
        {"q": "Comment s'appelle l'algue microscopique qui est à la base de toute la chaîne alimentaire marine ?", "options": ["Le zooplancton", "Le phytoplancton", "Le varech", "La posidonie"], "r": "Le phytoplancton"},
        {"q": "Quel pourcentage de l'oxygène que nous respirons est produit par les océans ?", "options": ["Environ 10%", "Environ 25%", "Environ 50%", "Environ 90%"], "r": "Environ 50%"},
        {"q": "Comment s'appelle le vent chaud et sec qui souffle du désert du Sahara vers l'Europe ?", "options": ["Le Mistral", "La Tramontane", "Le Sirocco", "Le Chinook"], "r": "Le Sirocco"},
        {"q": "Quel oiseau est connu pour pouvoir voler sans jamais se poser pendant près de 10 mois d'affilée ?", "options": ["Le martinet noir", "L'albatros", "L'hirondelle", "Le faucon pèlerin"], "r": "Le martinet noir"},
        {"q": "Quelle ère géologique est mondialement connue comme étant l'âge des dinosaures ?", "options": ["Le Paléozoïque", "Le Mésozoïque", "Le Cénozoïque", "Le Précambrien"], "r": "Le Mésozoïque"},
        {"q": "Quel est le plus petit oiseau du monde, pesant moins de 2 grammes ?", "options": ["Le colibri d'Elena", "Le roitelet", "La mésange bleue", "Le moineau domestique"], "r": "Le colibri d'Elena"},
        {"q": "Quelle est la plus longue chaîne de montagnes continentale au monde ?", "options": ["L'Himalaya", "Les Alpes", "Les Montagnes Rocheuses", "La Cordillère des Andes"], "r": "La Cordillère des Andes"},
        {"q": "Comment appelle-t-on le phénomène lumineux coloré qui se produit dans le ciel près des pôles magnétiques ?", "options": ["Un halo solaire", "Une aurore polaire", "Un mirage", "Une étoile filante"], "r": "Une aurore polaire"},
        {"q": "Quel animal possède la morsure la plus puissante du règne animal actuel ?", "options": ["Le requin blanc", "Le lion", "L'hippopotame", "Le crocodile marin"], "r": "Le crocodile marin"},
        {"q": "Comment s'appelle la science qui étudie spécifiquement la composition et la structure des roches ?", "options": ["La paléontologie", "La pétrologie", "La spéléologie", "La minéralogie"], "r": "La pétrologie"},
        {"q": "Quel est le nom de la fosse océanique la plus profonde, située dans l'océan Pacifique ?", "options": ["La fosse des Kouriles", "La fosse de Porto Rico", "La fosse des Mariannes", "La fosse des Tonga"], "r": "La fosse des Mariannes"},
        {"q": "Quelle échelle est couramment utilisée pour mesurer la magnitude d'un séisme ?", "options": ["L'échelle de Richter", "L'échelle de Beaufort", "L'échelle de Fujita", "L'échelle de Kelvin"], "r": "L'échelle de Richter"},
        {"q": "Quel poisson est réputé comme étant le plus rapide des océans ?", "options": ["L'espadon-voilier", "Le grand requin blanc", "Le thon rouge", "Le barracuda"], "r": "L'espadon-voilier"},
        {"q": "Quel animal a des empreintes digitales tellement semblables à celles des humains qu'elles peuvent tromper des enquêteurs ?", "options": ["Le koala", "Le chimpanzé", "Le raton laveur", "Le paresseux"], "r": "Le koala"},
        {"q": "Quelle période géologique est souvent appelée 'l'âge des poissons' ?", "options": ["Le Dévonien", "Le Jurassique", "Le Cambrien", "Le Carbonifère"], "r": "Le Dévonien"},
        {"q": "Quel est l'élément chimique le plus abondant dans la croûte terrestre ?", "options": ["L'oxygène", "Le fer", "Le silicium", "Le carbone"], "r": "L'oxygène"},
        {"q": "Comment appelle-t-on une relation entre deux espèces où les deux tirent profit de l'interaction ?", "options": ["Le mutualisme", "Le parasitisme", "Le commensalisme", "La compétition"], "r": "Le mutualisme"},
        {"q": "Quel est le nom scientifique des animaux qui pondent des œufs ?", "options": ["Les ovipares", "Les vivipares", "Les ovovivipares", "Les marsupiaux"], "r": "Les ovipares"},
        {"q": "Quel est le plus grand requin existant, qui se nourrit pourtant de plancton ?", "options": ["Le requin-baleine", "Le requin blanc", "Le requin tigre", "Le requin pèlerin"], "r": "Le requin-baleine"},
        {"q": "Quel est le nom de la science qui étudie spécifiquement les insectes ?", "options": ["L'entomologie", "L'arachnologie", "L'herpétologie", "L'ornithologie"], "r": "L'entomologie"},
        {"q": "Quel mammifère détient le record de la tension artérielle la plus élevée (nécessaire pour envoyer le sang à son cerveau) ?", "options": ["La girafe", "L'éléphant", "La baleine bleue", "Le guépard"], "r": "La girafe"},
        {"q": "Quel est le seul continent au monde où l'on ne trouve aucune espèce de fourmi indigène ?", "options": ["L'Antarctique", "L'Australie", "L'Europe", "L'Amérique du Sud"], "r": "L'Antarctique"},
        {"q": "Comment s'appelle l'arbre endémique de Socotra qui a la forme d'un parapluie inversé et possède une sève rouge sang ?", "options": ["Le dragonnier", "Le baobab", "L'araucaria", "Le banian"], "r": "Le dragonnier"}
    ]
}